travis:
  secure:
    BINSTAR_TOKEN: YgTbb1MEUVbutRUvjmJQqz2CZRaMtl7u1ohFuwHGAO6ARIlAZQ1ho8RbDd82eBNOBSiL58zt9MzrWVaLlrWyMdJOUUzbwaomiDoVXpLCZ+pL4W/vVqnDdPBr87kZEum/XsLgKs1KxWbKmfSMcTX4eQK8Tf2IQStFC+Q4xX5me1ZTU3dUeEzaJuyCQOav868dNd8qv2y2AP5p+9k+Wftnn2nf2QB52YdCCBblgmKf12yAbWvZJ+PX081dW8FdF9qL5ppNOxbkVovmfTJk8WZ0oLla4ICBJGYzJX2A15qN8fpHIwUmW3/FdOymTiXyglKEy9+ErW11ifr2lI030iFLEIK1XXTWs7OFWp6shT0gqaLxH0d4Xh9M0PBrnI0Tu5tVU+zqmp2tt2iBtUGSGV02cXjBWe+o+HJx6w6LSpD6kncn0cLNKaJKXOtEjrCre1NcQ6f7UIQ+MG5l/H2ryh9YLeoyji1qBCMDgmklBU/qFkuR1sushHsYBNOrtdvSOZop8catI/l88H1MmoT7ZSDu4849tQdFG8WZlVHyNmYfjj52tS+4ci/Z4vOHqPa3umKL1nUl1mtXE/GH0fUOYLPa0yPZGblvLu2Fk7lnN8dpFdsi7bw/yJxxVEjEBULhvUC2/1B3OwKveXYGPGyOcfkvRWDY/YeSYjVbqxe/+6DRvL4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
