travis:
  secure:
    BINSTAR_TOKEN: aIZRiM/ENIsVSc2CHewUKpkBIn34E3+4MmMgW1W93w2ZvOBvHquM9USvN3H4xjoB3haAsRlXbkOn48BWb0jEtb0CkF6TviL9uut8rJrwc5/0OulNGeaD7Q61C1/CNq+vhRNGk6gWFjEBG2UclNRVOpp0jm2ZMohxUdeG9lvfL75vF5ca0HHxEFvE4efino/l8lZ//4bcwnaIePy0EYBwTq9EgOnoNCdLOilmpP5Tw+DAyZrMxm6B3eO+VcbRcJ1gGZEb0xtvypDttPOmZz6Ib+vd+Rzo62EbZs0PxwzosyOPUnAVV/z00jet7GxJnF5tZlWMuqL+uZvkZz5u1BDq9zPfBznbtU5Ubx3+vjEIOdY/txeAfEU9c+yc1t2g3VcX0+Bl4WAQ86uCbhISV3PTO8/zrDgJUEIvGERnnbqZcUCSYuZMLIySi5GKmveD7Cm+L3TDUZUWkdGjsk1TwAncv3BKdAQDeqbkqvnQW96874utJXTcZmCiZbKB9gKiM3ZsZU/pw2eDu9Oxn+8HLKWLVLDWLJULfyjVpBfDu3fNp4By9hMs0+cvk4tn2+Xr4kjUU4SqRuTGqdzHZc0VJwnW06Yyo3YHwL1UxtvZm3ZncpJKAuvMkfRdFvyfRuKSBIE7EXSM7Lsp61rIQqnLfvGjts9KDPO4trxSrSKJvssHehY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
