travis:
  secure:
    BINSTAR_TOKEN: DC0w7iQrzetBycQRjhcNtOuGe80dRCle0xF3weuutSfEDIs1DGvaowiO7Pdvm3JhUHEYtT8f7hEUL4ExofnLnlonMAVBm+JsMm+cEmtAVFlvacj5+bk2sucRAuwtdqcNuxoLMYl/W3T6i6hBZLYfaHmVF1OYxJUkFXSD1HZ9FGxbsNOaoVKinD05WMR+ErxVh2lmN8v+2LvZdlH9KZ3jPkgj+6MWtxsj1Zzbzr2PxDgvWK+NO/Xi540JxYbuP4+09ZMFfQwM+QOQkXQqsLfSGkfzc6RpNCYBq0HMfM2U5Rv07Z3pV33pBWnOmnz+3wOdrlizS+3n1YXDRMjuKvXp73GYGphrG/Lm+UmiTlVR5QTuZ8pOHjaasZh55R/tp+9b9Uswe6zQqWqgAqlVo5sY79hOQ7Pvz5RVbO3/7WHXoHLPrAKnBJvyMB2yJQkLiThF+FJAaH2n8fdAJL04OSJwwBX1b1tCnwkRkhZFNUTKAptdGCVscAMRG2m9YkC8VN2IX8FeZ8h988r/rm0vfPL1nlqmpzhESwL8l8406uO+iK0pfCa4PtiL8Vm0N9VSFYdyZUO+KFeHSXPcjPi0ATkB5kmX44RXs05eOxdePTu4xkP51WQLFjd1acE/lZDHDH/c1tbXTd5lusOpmaCPP9VkY1dGjYc+kKr90OmkapY8Wsg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
