travis:
  secure:
    BINSTAR_TOKEN: EXkLtqwvAyUgxPR9QNuAJS+4T4yoYeeWfi6yLzN2qtoVIhKX/ootgi2hRjmaHpChi1P9l+0LNk1UKW/P4qdO2tc5DTCkNoxH5MMrIqq01adFUUBfb6skVpEjntIiWz0w2/BuVmI5wAl3SIoo5vpgMoieK9ZdqQB7bvOxZ9xVfEZzkgN30tTFi390CegMeLNBy6dOdcxMGT9tXvX6yGr/MOOTrNWQeMmqovVI5a/mx9Z3ks60Kl4EwwGKdrblToVjIxgndK2DYkz3BeiVQG8UyprsjqF+hUdC1NyIJ2+FyF9/SeVI5lfPcRJzAQuxqwENH+Fp7PofkJHw5J0BZKi72REcmI4lwl5xmZ2+jjeQf6os75cD5PJZrCkELYZLJLfuAvZPRewxlsTm/3EcroMMXCBDNrvln3Qe6M36eaPWr9mszkTcj+DNC410USzIBCsfY8zWpiyq6kU6KT1lfmW3NP8IKBU0bbNpdJgJJ5RJN3hqSImievO5NBej8Gdvw3O88fzUXxoUpTon5ZO+DvQsnre52IJ1AsmZU+lu+7wHuu/IUa3s+qspdMriKLa3+UfOCbWNgVlHAkJotumzKgeSHDlI9UTCwa9B9alOQad/EmPoqM+/fesX/L2q4y4Bcds84ktZdsxEAyqXoDkx6K+pxj5COk/CLIB3/uGj+isUbsg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
